language: bash

services:
  - docker

script:
  - docker-compose -v
  - cd docker && docker-compose run --rm -e JEKYLL_ENV=production site bundle exec jekyll build --source /code/

deploy:
  - provider: script
    skip_cleanup: true
    script: docker-compose run --rm -e FTP_PASS -e FTP_TARGET -e FTP_USER site /code/docker/deploy.sh
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: $TRAVIS_BUILD_DIR/docker/mdeploy-run.sh
    on:
      all_branches: true
