sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v

script:
  - docker-compose run --rm -e JEKYLL_ENV=production jekyll jekyll build

deploy:
#  - provider: script
#    skip_cleanup: true
#    script: ./deploy.sh
#    on:
#      tags: true
  - provider: script
    skip_cleanup: true
    script: ./mdeploy.sh
#   on:
#     tags: true
#     all_branches: true
#     condition: "$TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$"
