sudo: required

language: bash

services:
  - docker

addons:
  apt:
    packages:
    - lftp

before_install:
  - docker-compose -v
  - curl --version

script:
  - cd docker && docker-compose run --rm -e JEKYLL_ENV=production site bundle exec jekyll build --source /code/

deploy:
  - provider: script
    skip_cleanup: true
    script: $TRAVIS_BUILD_DIR/docker/deploy.sh
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: $TRAVIS_BUILD_DIR/docker/mdeploy-run.sh
    on:
      all_branches: true
