sudo: required

language: bash

services:
  - docker

addons:
  apt:
    packages:
    - lftp

before_install:
  - docker-compose -v
  - curl --version

script:
  - cd _docker && docker-compose run --rm -e JEKYLL_ENV=production jekyll jekyll build

deploy:
  - provider: script
    skip_cleanup: true
    script: $TRAVIS_BUILD_DIR/_docker/deploy.sh
  - provider: script
    skip_cleanup: true
    script: $TRAVIS_BUILD_DIR/_docker/mdeploy-run.sh
#    on:
#      tags: true
#   on:
#     tags: true
#     all_branches: true
#     condition: "$TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$"
