defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "main"
      pdf: true

url: "https://odinuv.com"

exclude:
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: compressed

gems:
  - jekyll-sitemap