defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "main"
      pdf: true

url: "https://odinuv.com"
#url: "https://akela.mendelu.cz"
#baseurl: "/~xpopelka/"

exclude:
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - deploy.sh
  - mdeploy.sh
  - .travis.yml
  - replace.sh

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-plantuml
  - jekyll-redirect-from  