version: '2'

services:
  jekyll:
    build: .
    image: quay.io/odinuv/site-jekyll 
    tty: true
    stdin_open: true
    volumes:
      - ../:/code
    working_dir: /code
    ports:
      - "4000:4000"
    command: jekyll serve --watch -H 0.0.0.0 --force_polling
  deploy:
    build: .
    image: quay.io/odinuv/site-jekyll 
    tty: true
    stdin_open: true
    environment:
      - MFTP_USER
      - MFTP_PASS
      - MFTP_TARGET
    volumes:
      - ../:/code
    working_dir: /code
    ports:
      - "4000:4000"
    command: /code/_docker/mdeploy.sh
